openapi: 3.0.0
info:
  title: Pricing API
  version: 1.0.0
  description: API to Dynamically calculate delivery pricing
paths:
  /price:
    post:
      summary: Calculate delivery price
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                zone:
                  type: string
                  minLength: 3
                  description: Zone code
                organization_id:
                  type: string
                  minLength: 1
                  description: Organization ID
                total_distance:
                  type: number
                  minimum: 1
                  description: Total distance in kilometers
                item_type:
                  type: string
                  enum:
                    - perishable
                    - non-perishable
                  description: Type of item
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_price:
                    type: number
                    description: Total price for the delivery
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        msg:
                          type: string
                          description: Error message
                        param:
                          type: string
                          description: Parameter name
                        location:
                          type: string
                          description: Location of the parameter in the request
        '404':
          description: Pricing not found for the given parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
servers:
  # Added by API Auto Mocking Plugin
  - description: local
    url: http://localhost:5000